spring:
  application:
    name : Project_PSS
  datasource:
    url: jdbc:postgresql://10.0.0.9:5432/project_pss
    username: postgres
    password: password2
    driverClassName: org.postgresql.Driver


server:
  port: 9090

